import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useAuth } from "@/contexts/AuthContext";
import type { Database } from "@/lib/database.types";

type OrderStatus = Database["public"]["Enums"]["order_status"];
type DeliveryMethod = Database["public"]["Enums"]["delivery_method"];
type PaymentMethod = Database["public"]["Enums"]["payment_method"];

export interface CreateOrderParams {
  sellerId: string;
  items: {
    productId: string;
    variantId?: string;
    sellerId: string;
    productName: string;
    productImage: string;
    variantName?: string;
    quantity: number;
    unitPrice: number;
  }[];
  shipping: {
    fullName: string;
    phone: string;
    city: string;
    subCity: string;
    woreda: string;
    houseNumber?: string;
    additionalInfo?: string;
    addressId?: string;
  };
  deliveryMethod: DeliveryMethod;
  deliveryFee: number;
  paymentMethod: PaymentMethod;
  notes?: string;
}

export const useOrders = (status?: OrderStatus) => {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["orders", user?.id, status],
    queryFn: async () => {
      if (!user) return [];
      let query = supabase
        .from("orders")
        .select(`
          *,
          order_items(*),
          payments(method, status, amount)
        `)
        .eq("user_id", user.id)
        .order("created_at", { ascending: false });

      if (status) query = query.eq("status", status);

      const { data, error } = await query;
      if (error) throw error;
      return data ?? [];
    },
    enabled: !!user,
  });
};

export const useOrder = (orderId: string) => {
  return useQuery({
    queryKey: ["order", orderId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("orders")
        .select(`
          *,
          order_items(*, products(name, product_images(url, is_primary))),
          payments(*),
          seller_profiles(company_name, city, is_verified)
        `)
        .eq("id", orderId)
        .single();

      if (error) throw error;
      return data;
    },
    enabled: !!orderId,
  });
};

export const useSellerOrders = (sellerId: string, status?: OrderStatus) => {
  return useQuery({
    queryKey: ["seller-orders", sellerId, status],
    queryFn: async () => {
      let query = supabase
        .from("orders")
        .select(`*, order_items(*), profiles(full_name, phone)`)
        .eq("seller_id", sellerId)
        .order("created_at", { ascending: false });

      if (status) query = query.eq("status", status);

      const { data, error } = await query;
      if (error) throw error;
      return data ?? [];
    },
    enabled: !!sellerId,
  });
};

export const useCreateOrder = () => {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (params: CreateOrderParams) => {
      if (!user) throw new Error("Must be logged in");

      const subtotal = params.items.reduce((sum, item) => sum + item.unitPrice * item.quantity, 0);
      const total = subtotal + params.deliveryFee;

      // Create order (order_number auto-generated by trigger)
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          user_id: user.id,
          seller_id: params.sellerId,
          order_number: `TEMP-${Date.now()}`, // will be overwritten by trigger
          status: "pending",
          subtotal,
          delivery_fee: params.deliveryFee,
          discount: 0,
          total,
          currency: "ETB",
          address_id: params.shipping.addressId ?? null,
          shipping_full_name: params.shipping.fullName,
          shipping_phone: params.shipping.phone,
          shipping_city: params.shipping.city,
          shipping_sub_city: params.shipping.subCity,
          shipping_woreda: params.shipping.woreda,
          shipping_house_number: params.shipping.houseNumber ?? null,
          shipping_additional_info: params.shipping.additionalInfo ?? null,
          delivery_method: params.deliveryMethod,
          notes: params.notes ?? null,
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const { error: itemsError } = await supabase.from("order_items").insert(
        params.items.map((item) => ({
          order_id: order.id,
          product_id: item.productId,
          variant_id: item.variantId ?? null,
          seller_id: item.sellerId,
          product_name: item.productName,
          product_image: item.productImage,
          variant_name: item.variantName ?? null,
          quantity: item.quantity,
          unit_price: item.unitPrice,
          total_price: item.unitPrice * item.quantity,
        }))
      );

      if (itemsError) throw itemsError;

      // Create payment record
      const { error: paymentError } = await supabase.from("payments").insert({
        order_id: order.id,
        user_id: user.id,
        method: params.paymentMethod,
        status: "pending",
        amount: total,
        currency: "ETB",
      });

      if (paymentError) throw paymentError;

      // Send notification to seller
      await supabase.from("notifications").insert({
        user_id: params.sellerId,
        type: "order",
        title: "New order received!",
        body: `You have a new order worth ${total.toLocaleString()} ETB`,
        data: { order_id: order.id },
        action_url: "/seller-dashboard",
      });

      return order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      queryClient.invalidateQueries({ queryKey: ["cart"] });
    },
  });
};

export const useUpdateOrderStatus = () => {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({
      orderId,
      status,
      cancelReason,
    }: {
      orderId: string;
      status: OrderStatus;
      cancelReason?: string;
    }) => {
      const updates: Record<string, unknown> = { status };
      if (status === "cancelled") {
        updates.cancelled_at = new Date().toISOString();
        updates.cancel_reason = cancelReason ?? null;
      }
      if (status === "delivered") {
        updates.delivered_at = new Date().toISOString();
      }

      const { data, error } = await supabase
        .from("orders")
        .update(updates)
        .eq("id", orderId)
        .select("*, user_id")
        .single();

      if (error) throw error;

      // Notify buyer
      await supabase.from("notifications").insert({
        user_id: data.user_id,
        type: "order",
        title: `Order ${status}`,
        body: `Your order #${data.order_number} has been updated to: ${status}`,
        data: { order_id: orderId },
        action_url: "/dashboard",
      });

      return data;
    },
    onSuccess: (_, { orderId }) => {
      queryClient.invalidateQueries({ queryKey: ["order", orderId] });
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      queryClient.invalidateQueries({ queryKey: ["seller-orders"] });
    },
  });
};

export const useAdminOrders = (filters: { status?: OrderStatus; search?: string } = {}) => {
  return useQuery({
    queryKey: ["admin-orders", filters],
    queryFn: async () => {
      let query = supabase
        .from("orders")
        .select(`*, profiles(full_name, email), seller_profiles(company_name)`)
        .order("created_at", { ascending: false });

      if (filters.status) query = query.eq("status", filters.status);

      const { data, error } = await query;
      if (error) throw error;
      return data ?? [];
    },
  });
};
